### ISSUE TITLE
Members api deprecate

### ISSUE THREAD

**Issue by Muralidhar22** [Real-Dev-Squad/website-todo-items#110]
# Proposed Workflow
Currently, both [/members](https://api.realdevsquad.com/members) & [/users](https://api.realdevsquad.com/users) return all users data. So, it is better to have a single endpoint to return all users and more intuitive to have ```/users``` return it.

- Verify and make the response of [users](https://api.realdevsquad.com/users) endpoint similar to [members](https://api.realdevsquad.com/members) endpoint
- Update the API contract of [users](https://api.realdevsquad.com/users) endpoint if there are any changes
- Merge the backend PR of ```/users``` to staging environment.
- Create PRs in all frontend apps where [members](https://api.realdevsquad.com/members) endpoint is in use and update it to [users](https://api.realdevsquad.com/users) endpoint
- After merging ```/users``` on backend in staging enviroment, start testing on frontend across all RDS Apps in staging
- Verify everything is working fine in staging environment.
- Once verified, push the backend and frontend changes to the production environment respectively
- Monitor New Relic logs for a week to verify if [members](https://api.realdevsquad.com/members) endpoint is still in use or not
- Simultaneously work on deprecating [members](https://api.realdevsquad.com/members) endpoint.
- After monitoring, deprecate the [members](https://api.realdevsquad.com/members) endpoint permanently.
- Update the API contract of users to add a filter

## Progress
- [ ]  Verify and make the response of [users](https://api.realdevsquad.com/users) endpoint similar to [members](https://api.realdevsquad.com/members) endpoint
- [ ]  Update the API contract of [users](https://api.realdevsquad.com/users) endpoint if there are any changes
- [ ]  Merge the backend PR of ```/users``` to staging environment.
- [ ]  Create PRs in all frontend apps where [members](https://api.realdevsquad.com/members) endpoint is in use and update it to [users](https://api.realdevsquad.com/users) endpoint
- [ ]  After merging ```/users``` on backend in staging enviroment, start testing on frontend across all RDS Apps in staging
- [ ]  Verify everything is working fine in staging environment.
- [ ]  Once verified, push the backend and frontend changes to the production environment respectively
- [ ]  Monitor New Relic logs for a week to verify if [members](https://api.realdevsquad.com/members) endpoint is still in use or not
- [ ]  Simultaneously work on deprecating [members](https://api.realdevsquad.com/members) endpoint.
- [ ]  After monitoring, deprecate the [members](https://api.realdevsquad.com/members) endpoint permanently.
- [ ]  Update the API contract of users to add a filter

### frontend

- [ ]  Dashboard site
   - [x] Issue: https://github.com/Real-Dev-Squad/website-dashboard/issues/237

### backend
- [x] https://github.com/Real-Dev-Squad/website-backend/issues/608
- [ ] https://github.com/Real-Dev-Squad/website-backend/issues/761

**Comment by RitikJaiswal75** [comment]
closing in lieu of: https://github.com/Real-Dev-Squad/website-members/issues/547

**Comment by prakashchoudhary07** [comment]
Refer https://github.com/Real-Dev-Squad/website-members/issues/547
