### ISSUE TITLE
FIX words count during signup

### ISSUE THREAD

**Issue by iamsonukushwaha** [Real-Dev-Squad/website-todo-items#164]
Kindly fix this issue, it should be characters but it is asking for words.

![image](https://github.com/Real-Dev-Squad/todo-action-items/assets/51280276/a63492f3-2da7-4cb3-8621-560bf1ea8a05)

![image](https://github.com/Real-Dev-Squad/todo-action-items/assets/51280276/0bab1a88-6237-49c9-b335-1775aeb826fb)

**Comment by RitikJaiswal75** [comment]
@flyingsonu122 We intend it to be 100 words not characters.

**Comment by iamsonukushwaha** [comment]
ok
