### ISSUE TITLE
Google cloud setup for tiny site backend 

### ISSUE THREAD

**Issue by vinit717** [Real-Dev-Squad/website-todo-items#207]
### **Description**
Tiny site is currently using Google authentication for login to setup the Google client Id and client secret below are the steps to set it up

### Then create a new project or if we already have a project create OAuth 2.0 Client IDs under API/credentials
 
![image](https://github.com/Real-Dev-Squad/todo-action-items/assets/111434418/cbe80d7a-e32c-4b98-b0c2-26e028aa2809)
![image](https://github.com/Real-Dev-Squad/todo-action-items/assets/111434418/6fcfaa25-68f7-484f-aab4-f439430819bd)
![image](https://github.com/Real-Dev-Squad/todo-action-items/assets/111434418/9ecc73fd-71d3-4f6f-8795-e0636f983e16)

### this https://services.realdevsquad.com/tinysite/v1/auth/google/callback

![image](https://github.com/Real-Dev-Squad/todo-action-items/assets/111434418/3128a491-e61c-4abf-a514-4c7f9b6ade2b)

### - Download the JSON and go the https://github.com/Real-Dev-Squad/tiny-site-backend/settings/environments  /prod  and edit client_id and client_secret with the exact value
![image](https://github.com/Real-Dev-Squad/todo-action-items/assets/111434418/4010c287-e394-414a-bd34-5ffa51f61ce9)

### - Check Publishing status to be Production

![image](https://github.com/Real-Dev-Squad/todo-action-items/assets/111434418/7780d4ba-fb14-4546-a872-9e433fb664ac)

**Comment by ankushdharkar** [comment]
Thank you for the steps @vinit717. 

✅I have added the two keys in the following env secrets:

<img width="329" alt="image" src="https://github.com/Real-Dev-Squad/todo-action-items/assets/1935403/8b64c613-196b-4691-9d04-454af327c0b8">
