### ISSUE TITLE
Remove CI checking on node versions 10.x and 12.x across all repos

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-todo-items#23]
Since node version 14 is LTS and Heroku is also using node v14, we don't need to run the CI checks on node v10 and v12

**Comment by Cartmanishere** [comment]
These are the repos that use node version in the github action:

  - [X] Website-status
  - [x] Website-backend
    + https://github.com/Real-Dev-Squad/website-backend/pull/319
  - [x] Website-my
    + https://github.com/Real-Dev-Squad/website-my/pull/83
  - [x] Website-members
    + https://github.com/Real-Dev-Squad/website-members/pull/156
  - [x] website-crypto
    + https://github.com/Real-Dev-Squad/website-crypto/pull/201
  - [X] website-welcome

**Comment by swarajpure** [comment]
All PRs merged. Thank you @Cartmanishere
