### ISSUE TITLE
Remove /arts/user/self and implement a new available API Endpoint

### ISSUE THREAD

**Issue by vikasosmium** [Real-Dev-Squad/website-todo-items#260]
### Issue Description

Remove /arts/user/self and implement a new available API Endpoint /arts/:userId across all repos.

- Reference: https://github.com/Real-Dev-Squad/website-backend/pull/2255

Below is the mentioned list of repos where arts/user/self is currently being used:
1. - [ ]     
2. - [ ]     

### Expected Behavior

We should have removed the usage of /arts/user/self API Endpoint and should be using new API endpoint /arts/:userId.

### Current Behavior

Currently, we are using the /arts/user/self API Endpoint.

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. Go to every repo and check where we are using and calling /arts/user/self.

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by mdansarijaved** [comment]
@vikasosmium  I created a TCR for this repo please assign this issue to me thanks

**Comment by mdansarijaved** [comment]
Didn't find any use case of this repository as of now. Searched through these repositories @vikasosmium 
![image](https://github.com/user-attachments/assets/a3662f44-a529-4251-b370-060693bf7afe)

**Comment by vikasosmium** [comment]
Okay, I am closing this issue now because this API is not currently being used.
