### ISSUE TITLE
[RFC] Profile service implementation language

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-todo-items#32]
Let's do pros and cons between:
- Java
- Go
- Rust
(no Node, since our main backend is in NodeJS already)

**Comment by lakshayman** [comment]
https://discord.com/channels/673083527624916993/729399523268624405/911298808930000987

link to discussion

**Comment by lakshayman** [comment]
@ankushdharkar I think Go would be a better option as jeet suggested it is a perfect fit for what we are doing
Also, you said It is friendlier than Rust
We can consider Java too but I personally want to explore Go

**Comment by rohan09-raj** [comment]
> @ankushdharkar I think Go would be a better option as jeet suggested it is a perfect fit for what we are doing Also, you said It is friendlier than Rust We can consider Java too but I personally want to explore Go

@ankushdharkar @lakshayman 
1) Java is more complex and consumes more time to learn and as a result development time will be more while Golang is quick and easy to learn, which means we can build this feature in a shorter duration of time.
2) Golang also has faster server response and compilation time than Rust and Java.
Comparison between Rust and Golang :
https://medium.datadriveninvestor.com/rust-versus-golang-is-good-rust-for-web-development-1a104a5c8b6
Comparison between Java and Golang :
https://www.miquido.com/blog/golang-vs-java/

**Comment by aman7870** [comment]
@lakshayman @rohan09-raj 
So, we are going with GO or JAVA language??

**Comment by aman7870** [comment]
Upon comparing Java, Go and Rust for profile service feature:

Go is fast, scalable as compared to the other two
https://www.educba.com/go-vs-java/
https://appinventiv.com/blog/go-vs-rust-choice-for-app-development/

**Comment by lakshayman** [comment]
As above discussed, Go is fast, scalable, and the best suitable language for what we are making

So, Let's Go with Go
