### ISSUE TITLE
[RFC] Logging service

### ISSUE THREAD

**Issue by whyDontI** [Real-Dev-Squad/website-todo-items#34]
# Idea
- A service for logging every action on web apps
- We need to show audit history in [tasks](https://github.com/Real-Dev-Squad/website-status/issues/211) and [storycard](https://github.com/Real-Dev-Squad/website-status/issues/115) components

# What can be logged as history
- Any kind of update in tasks
  - Update/Add assignee
  - Update due date
  - Update title, description
- Any Transaction of crypto coins

**Comment by whyDontI** [comment]
@ankushdharkar @ankurnarkhede @swarajpure @saxenaaman628

**Comment by pallabez** [comment]
Logging service implemented. To know more 
- https://github.com/Real-Dev-Squad/website-todo-items/issues/49
