### ISSUE TITLE
Create indexes in firestore

### ISSUE THREAD

**Issue by akshay1502** [Real-Dev-Squad/website-todo-items#58]
Create indexes for `task` collection for following fields
- assignee `ascending` startedOn `descending`
- participants `[]` status `ascending` startedOn `descending`
- participants `[]` startedOn `descending`
- assignee `ascending` status `ascending` startedOn `descending`

## Steps: 
1. Go to indexes in firestore
2. Click `Add Index`
3. Enter collection ID 
4. Enter fields and choose type of ordering
5. Select query scope(`collection` for our case) and create index

eg
![Screenshot 2022-03-05 at 23-11-21 rds-backend – Cloud Firestore – Firebase console](https://user-images.githubusercontent.com/55057874/156894532-8df3b233-5324-4946-b5f8-ee196279b72d.png)
.

**Comment by ankushdharkar** [comment]
@akshay1502 Initiated creating the indexes. ✅
Thank you for the instructions.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/1935403/158020421-3e200feb-de1d-4eab-bf98-51c752042428.png">
